Fix/migrations
wecode-bootcamp-korea/38-2nd-WeToBee-backend pull request #5
Opened 2022-11-03 03:48 UTC by tlacodnjs667

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
 - 테이블 내 정보 변경 위한 PR입니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 스팟의 지점들이 JSON형태로 (위, 경도, 마커, ..) 들어와야 하기 때문에 `spot_savings` 의 위 경도 컬럼을 삭제하고 spot_data라는 컬럼을 추가하여 데이터가 담길 수 있도록 하였습니다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- ALTER TABLE을 할 경우, 한 변경에 ADD나 DELETE, MODIFY 중 하나만 사용할 수 있다고 생각했는데 그게 아니란 것을 알게 되었습니다.
<br />

## :: 기타 질문 및 특이 사항
- 프론트가 맵에 대한 정확한 이해를 할 경우, 들어가는 데이터가 또 변경될 수 있을 것 같습니다.

2022-11-03 08:20 UTC, kyeongraekim requested changes

2022-11-03 08:20 UTC, kyeongraekim commented on db/migrations/20221103023609_alter_spot_savings_table.sql
> +    DROP spot_data JSON NOT NULL;
위도 경도 내용을 DROP 하게된 기획 변경 소요가 있으실까요?

2022-11-03 16:07 UTC, tlacodnjs667 commented on db/migrations/20221103023609_alter_spot_savings_table.sql
> +    DROP spot_data JSON NOT NULL;
위도 경도 내용을 담은 JSON 데이터를 저장할 예정입니다. 위도와 경도 말고 icon type 등의 다양한 정보를 DB에 저장해야 하고, 똑같은 상태로 반환을 해야 마커를 찍을 수 있다고 해서요!
사진 정보 첨부합니다!
<img width="393" alt="image" src="https://user-images.githubusercontent.com/114975208/199772159-d42afd9b-2c21-4d02-baa2-a4405d5f302f.png">

2022-11-04 01:43 UTC, kyeongraekim approved these changes
LGTM!~

2022-11-04 01:43 UTC, merged