Feature/review
wecode-bootcamp-korea/38-2nd-WeToBee-backend pull request #7
Opened 2022-11-03 16:54 UTC by tlacodnjs667

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰 엔드포인트를 생성, 조회 (메인 리뷰 이미지, 플랜 디테일 페이지 내 댓글), 삭제 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰 생성 API
- 구매 내역이 있는 유저에게만 생성 권한 부여하는 서비스 로직 구현

2. 리뷰 조회 API(메인 페이지)
-  리뷰 이미지들을 리뷰 like를 많이 받은 순서로 정렬하여 반환
-  해당 plan이나 review로 이동할 수 있도록 plan id와 review id, thumbnail 반환

3. 리뷰 조회 API(플랜 상세 페이지) 
- 각 플랜에 작성된 review 반환

4. 리뷰 삭제 API
- 리뷰의 작성자만 삭제 가능하도록 서비스 로직 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 많은 경우의 수를 생각하며 서비스 로직들을 구현했던 것 같습니다. 실제 현업에서는 어떤 기준을 부여하는지 궁금합니다.

<br />

## :: 기타 질문 및 특이 사항
- 아직 review image의 파일형태가 정해지지 않아 수정이 필요할 것 같습니다. 
   또한 userId가 어떤 방식으로 들어오는 지 몰라 위 두가지 방식을 제외하여 API를 구성하였습니다.
   
- 엔드 포인트 구현 시 HTTP 메소드 중 GET 요청이 2개라 path parameter를 통해 분기를 생성하였는데, 
   `/plans`와 `/images`라는 path parameter가 마음에 들지 않아 멘토님의 조언을 구합니다..
   
   `/plans` : 플렌 디테일 페이지에서 조회되는 API 분기입니다. 리뷰 콘텐츠와, 리뷰 썸네일, 리뷰 작성자의 닉네임을 반환합니다.
   `/images` : 메인 페이지에서 조회되는 API 분기입니다. 리뷰 이미지들을 무한 스크롤로 구현하려 합니다.

2022-11-04 02:31 UTC, kyeongraekim requested changes

2022-11-04 02:31 UTC, kyeongraekim commented on api/controllers/reviewController.js
> +}) //보류
- 불필요한 주석문은 삭제해주세요~

2022-11-04 02:31 UTC, kyeongraekim commented on api/models/reviewDao.js
> +    `, [userId, planId, 2, content, thumbnail, title]);
- 중간에 숫자 2가 하드코딩 되어 들어가있네요! DEFAULT_CATEGORY_ID 정도의 추가 변수를 선언해서 하드코딩을 피해주세요~

2022-11-04 02:31 UTC, kyeongraekim commented on api/services/reviewService.js
> +        const error = new Error('YOU_ARE_NOT_OWNER');
- 서버에서 내는 에러메세지는 실사용자가 아닌 클라이언트/프론트엔드 차원에서의 확인 목적이 강함으로, 어떠한 에러임을 간단히 유추할 수 있는 메세지 등으로 바꾸어주세요!~

2022-11-04 02:31 UTC, kyeongraekim commented on api/services/reviewService.js
> +    if(checkPlanSelling[0].orderStatus !== 1){
- 주문에 대한 Status는 enum의 개념을 사용해서 별도의 파일, models/enums.js 에서 따로 관리 후 활용해주세요!
아래의 예시를 참고해주세요!~

```javascript
const orderStatusEnum = Object.freeze({
     ADDED : 1,
     CANCELED : 2
 });

 module.exports = { orderStatusEnum };

2022-11-04 02:31 UTC, kyeongraekim commented on api/services/reviewService.js
> +    const title = `I love this plan!`
해당 하드코딩 내용은 무엇인지 알려주세요!~

2022-11-04 10:09 UTC, tlacodnjs667 commented on api/services/reviewService.js
> +    const title = `I love this plan!`
프론트에서 리뷰에 대한 title을 넣지 않는데, db내에서 `not null` 조건이 걸려 있어 확인용으로 사용하기 위해 올렸습니다!
이후 migration fix 할 부분 있으면 수정 요청하여 다시 올리겠습니다!

2022-11-10 12:56 UTC, kyeongraekim approved these changes

2022-11-10 12:56 UTC, merged