order Endpoint 구현
wecode-bootcamp-korea/38-2nd-WeToBee-backend pull request #8
Opened 2022-11-04 13:41 UTC by tlacodnjs667

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-  플랜 구매 시, 결제 등의 수행 과정에 문제가 생기면 원 상태로 되돌리는 기능을 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.  플랜 결제 시 서비스 로직에 따라 에러 발생
- 요청한 유저의 플랜의 경우 에러 발생 (본인의 플랜 구매 불가)
- 해당 플랜의 판매 상태가 'for sale'로 한 상태인지 확인하고 아닌 경우 에러 발생
- 유저의 포인트가 플랜의 가격보다 많은가를 확인하고 적으면 에러 반환
- 유저가 동일한 플랜을 중복으로 구매하려 할 경우, 에러 발생

2. 트랜젝션 구현
- typeorm의 queryRunner를 통해 transaction 기능 구현
- 구매 기능 중간에 에러 발생할 경우, 처음 상태로 되돌리는 기능

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 처음에는 어렵게만 느껴졌던 transaction을 해결하고 나니 기분이 너무 좋습니다!
트렌젝션을 구현하고 에러를 실행하는 과정에서, 실행을 하지 않고 저장만 하는 것이 아니라, 실행을 한 후, 중간에 에러가 발생하면 처음 상태로 되돌리는 것이라는 것을 깨닫게 되었습니다. - 스스로 깨달아서 기분이 좋습니다!
하지만, entityManager와의 차이에 대해 이해하지는 못했습니다. 

<br />

## :: 기타 질문 및 특이 사항

2022-11-05 16:49 UTC, tlacodnjs667 commented
질문이 하나 있습니다! -> 이번 프로젝트 내에서 찜하기 기능을 구현하는 데이터가 review와 plan이 있습니다.
이전에는 like라는 엔드포인트를 생성해서 이러한 기능을 구현하였는데, 
이번에 생각해보니 최종반환하는 자원이 각각 리뷰와 플랜이기 때문에, like라는 엔드포인트를 따로 구성하는 것이 아니라 리뷰와 플랜 엔드포인트 내에 각각 like의 기능을 수행하는 API를 생성하는 것이 맞지 않나, 라는 궁금증이 생겼습니다!

2022-11-08 07:08 UTC, kyeongraekim requested changes

2022-11-08 07:08 UTC, kyeongraekim commented on api/controllers/orderController.js
> +   res.status(200).json({message : "ORDER_CREATED", data:orderId});
주문 생성에 대한 상태코드 다시 한 번 확인해주세요!~

2022-11-08 07:08 UTC, kyeongraekim commented on api/models/orderDao.js
> +
transaction의 시작부분또한 try-catch 구문안에 넣어주세요~ try 구문 전체가 흘러갈 때 에러가 날 때 발생하는 error를 활용해주셔야 합니다.

2022-11-08 07:08 UTC, kyeongraekim commented on api/services/orderService.js
> +    const orderStatus = [1,2];
- orderstatus 는 enum의 개념을 활용해서 가독성 좋게 활용해주세요!~ 
-  상수로 관리되는 데이터들은 보통 enum으로 관리하곤 합니다. JavaScript에서는 다음과 같이 객체 형태로 관리하게 됩니다.
 객체가 수정될 수 있기 때문에 상수 데이터 관리 목적과는 반대로 해당 값에 변형이 이루어질 수 있습니다. 따라서 JavaScript의 `Object.freeze()`를 활용합니다.
    
```javascript
const Departure = Object.freeze({
      GMP: 1,
      PUS: 2,
      ...
    })

2022-11-08 07:08 UTC, kyeongraekim commented on api/utils/orderStatusEnum.js
> +    "paid" : 2
상수데이터 네이밍 컨벤션은 대문자, snake_case가 기본원칙입니다.
해당 내용을 위에 재가 언급해드린 부분에서도 활용해주세요!~

2022-11-10 06:08 UTC, kyeongraekim requested changes

2022-11-10 06:08 UTC, kyeongraekim commented on api/models/orderDao.js
> +    `, [ORDER_STATUS['paid'], addedOrder.insertId]);
enum은 객채로 선언되기 때문에 ORDER_STATUS.PAID 형태로 접근 가능하실거에요  관련해서 한 번 수정해주세요!~

2022-11-10 08:00 UTC, kyeongraekim commented on api/utils/orderStatusEnum.js
> +    "paid" : 2
@tlacodnjs667 
아직 이부분 적용이 안되어있네요!

2022-11-10 08:00 UTC, kyeongraekim commented on api/models/orderDao.js
> +    `, [ORDER_STATUS['paid'], addedOrder.insertId]);
@tlacodnjs667 
아직 이부분 적용이 안되어있네요!

2022-11-10 10:07 UTC, kyeongraekim approved these changes
LGTM!~

2022-11-10 10:10 UTC, merged